port: 8080

db:
  host: 'localhost'
  port: 20178
  name: 'webshop'

logging:
  level: debug
  logPath: './_log'
  logMask: 'log,json'
  fileRotateConfig:
    filename: 'webshop-ts-backend%DATE%.log'
    datePattern: 'YYYY-MM-DD'
    json: false
    maxsize: 536870912
    #How many files to keep logs if there is only number, or how many days if there is 'd' sufix
    maxFiles: "7d"